[package]
edition = "2021"
name    = "banana_bevy_utils"
publish = false
version = "0.1.0"

[dependencies]
bevy          = { version = "0.8", default-features = false }
iyes_loopless = { version = "0.8.0" }

[features]
2d      = ["bevy/bevy_sprite", "bevy/bevy_winit"]
bevy_ui = ["bevy/bevy_ui"]
